### ISSUE TITLE
FinishCurrentPhase() throws a NullReferenceException

### ISSUE THREAD

**Issue by GingaaBread** [GingaaBread/Unity-Game-Jam-2022#12]
**Describe the bug**
The TimeManager script throws a NullReferenceException in the switch construct of the FinishCurrentPhase() function.

**To Reproduce**
1. Checkout the `ui-notification` branch
2. Play the _FinalBuild_ scene
3. Enqueue a test UI panel to the queue (under the Gamejam menu)
4. Force a time forward (under the Gamejam menu)
5. See error

**Expected behavior**
The phase should be finished as expected

**Screenshots**
Shows the bug happening
![t](https://user-images.githubusercontent.com/26445308/200201644-f6d43a7c-0175-4f20-922a-5458989939c1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Occurred after implementing icons to the notification panels. The tests worked before.

**Comment by ballardi** [comment]
explanation of issue here:
https://discord.com/channels/1035627564317818973/1036413213014757488/1039067285572296765
short answer is it's fixed in the branch in question. when that branch is merged to dev it'll be fixed everywhere.
