### ISSUE TITLE
using cards doesn't decrease player's money

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#130]
**Describe the bug**
When the player places cards, their cost is not subtracted from their total money in the shop.

**To Reproduce**
1. Check current money in the shop
2. Play any card
3. Open shop again to see that money has not decreased.

**Expected behavior**
When a player plays a card, it's cost should be deducted from their total money.

**Desktop (please complete the following information):**
 - Browser [chrome/brave]

**Comment by GingaaBread** [comment]
It was not a feature yet
