### ISSUE TITLE
city A shop prices

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#132]
**Describe the bug**
I sold wheat to city A and received a notification stating that I had gained 5 coins when I should have gained 12 coins. Not sure what the actual difference was in my money (sorry I forgot what number I had before I sold).

**To Reproduce**
1. Go to shop 
2. Sell wheat to city A
3. See notification

**Expected behavior**
City A should by crops at a premium. Wheat should be bought for 12 coins.

**Desktop (please complete the following information):**
 - Browser [chrome/brave]

**Comment by GingaaBread** [comment]
Fixed via PR
