### ISSUE TITLE
only drawing four cards 

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#133]
**Describe the bug**
At the beginning of year three fall, I started only drawing back to four cards rather than up to five. Somewhere in year three winter, I started only drawing three cards.

**To Reproduce**
1. I'm not sure, sorry ;_;

**Expected behavior**
I started only getting new cards up to four and then up to three (instead of up to five).

**Desktop (please complete the following information):**
 - Browser [chrome/brave]

**Comment by GingaaBread** [comment]
I experienced the same bug in year two. I sold items just before, maybe that's related?

**Comment by GingaaBread** [comment]
I think this is fixed? Feel free to reopen if not
