### ISSUE TITLE
tried to discard flower card but showed bee card?

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#134]
**Describe the bug**
I clicked the discard button on a flower card but it showed a preview of a bee card.

**To Reproduce**
1. I discarded a bee card earlier? not sure if this contributed to the issue
2. try to discard flower card
3. see the error 

**Expected behavior**
It should show a preview a flower card.

**Screenshots**
![Screenshot 2022-11-27 at 23 03 55 (2)](https://user-images.githubusercontent.com/119008588/204192491-ec38e1df-502c-49b0-9c97-6089f97f0e30.png)

**Desktop (please complete the following information):**
 - Browser [chrome/brave]

**Comment by GingaaBread** [comment]
Additional info: https://github.com/GingaaBread/Unity-Game-Jam-2022/issues/209#issue-1471858230
