### ISSUE TITLE
Player cannot end the turn (New way to get softlocked)

### ISSUE THREAD

**Issue by Crostz** [GingaaBread/Unity-Game-Jam-2022#136]
**Describe the bug**
Player gets stuck in the game because of a bug that involves the discarding card screen and the time panel.
(Player cannot end turn) Like, **the button is not locked**, but after clicking it the button cooldown appears but it doesn't go forward, so like, it doesn't end the turn and go to the next turn.

**To Reproduce**
1. Try discarding a card (Like, enter the discard screen where the trash bin is)
2. Don't discard just yet.
3. As soon as you click the discard button, end the turn immediately.
4. See error (Player gets stuck in the game because they can no longer end the turn)

**Expected behavior**
I expected the game to just keep going normally.

**Screenshots**
I dont have screenshots

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
To tackle this, I would make ending the turn impossible while choosing to discard a card

**Comment by GingaaBread** [comment]
Closed for now, feel free to reopen if this still happens in the future release
