### ISSUE TITLE
no notification when collecting livestock resources

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#142]
**Describe the bug**
No notification appears when I collect a resource from livestock (milk/wool/pork/fish/honey)
**EDIT:** this isn't working for pigs/pork but is working for bees/honey and fish/fish 

**To Reproduce**
1. place an animal pen
2. place livestock in the pen
3. wait until the livestock produces its byproduct/resource
4. do not receive notification

**Expected behavior**
The player should receive a notification when they collect resources from livestock 

**Desktop (please complete the following information):**
 - Browser [brave/chrome]

**Comment by GingaaBread** [comment]
Fixed, I believe? Reopen please if this is still wrong.
