### ISSUE TITLE
Shop says I don't have wheat that is marked in my inventory.

### ISSUE THREAD

**Issue by rohaid-bakh** [GingaaBread/Unity-Game-Jam-2022#145]
**Describe the bug**
I was trying to sell some wheat to a shop owner, but the dialogue said I didn't have any. The inventory said I had 1 wheat left. 

**To Reproduce**
1. Play up till Fall, Turn 1, Year 1 normally.
2. Click on Shop, Click on "Perry", sell flowers, and then try to sell wheat.
3. See error

**Expected behavior**
I expected to be able to sell the wheat.

**Screenshots**
Here is what my map looks like:
![image](https://user-images.githubusercontent.com/38147450/204388363-72803fc5-161b-432b-b3d1-e5a569ab2d68.png) 

Here is what the shop + inventory looked like 
![image](https://user-images.githubusercontent.com/38147450/204388462-4399f0b7-9d33-420e-9a9c-c9d7bea56275.png)

Here is what was said.
![image](https://user-images.githubusercontent.com/38147450/204388592-3fc5a2e9-337b-428f-b589-898b89348049.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 107.2

**Comment by GingaaBread** [comment]
That's not wheat. I've attached an image of the wheat icon:
![Resource_Wheat](https://user-images.githubusercontent.com/26445308/204397277-6e2e93c3-f942-46ea-8a7e-8d389c1fff30.png)
