### ISSUE TITLE
Money Received Notifications Appearing on Discard

### ISSUE THREAD

**Issue by samoncrief** [GingaaBread/Unity-Game-Jam-2022#153]
https://user-images.githubusercontent.com/51212088/204512889-120986f3-9fc1-4e8a-a97f-145fe434530b.mp4

When selling products in the store, opening the Discard window after causes the money received notifications to appear. These notifications should happen after exiting the store or at the start of a turn.

https://user-images.githubusercontent.com/51212088/204513628-ea240a22-46fe-4ca4-9fea-eba1d13aad62.mp4

Also attached is a soft lock possible due the ability to try to discard other cards during the notification sequence.

**Comment by ballardi** [comment]
fixed - will be in the next release
