### ISSUE TITLE
End Turn during Discard animation causes soft lock

### ISSUE THREAD

**Issue by samoncrief** [GingaaBread/Unity-Game-Jam-2022#154]
https://user-images.githubusercontent.com/51212088/204518349-aef513c0-ea5c-4994-87bb-975f1faab2c5.mp4

Since the "End Turn" panel can be interacted with during the Discard animation, a soft lock can be triggered using the steps in the attached video. The hand is stuck at 4 cards, Discard does not refresh, and the End Turn button does not work.

**Comment by ballardi** [comment]
hopefully fixed. closing but after the next build gino makes, please do create a new ticket if you see that problem happen again.
