### ISSUE TITLE
end turn button not working

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#171]
**Describe the bug**
When I click end turn, the animation plays but the turn doesn't change. I think this might be because I sold things in the shop before I played cards.
EDIT: I got the same issue when I clicked "end turn" while a card was discarding.

**To Reproduce**
1. start turn
2. go to shop
3. sell something
4. play cards
5. click end turn

**Expected behavior**
When you click end turn, the turn should change to the next one.

**Screenshots**
https://user-images.githubusercontent.com/119008588/204708292-60764896-e432-47b7-8640-84386621def7.mov

**Desktop (please complete the following information):**
 - Browser [brave/chrome]

**Comment by GingaaBread** [comment]
related to the queue

**Comment by GingaaBread** [comment]
also animation states

**Comment by GingaaBread** [comment]
Fixed
