### ISSUE TITLE
i keep getting the same quests

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#190]
**Describe the bug**
Reloaded the game three times. I'm getting the same quests every time.

**To Reproduce**
1. Open game
2. See quests "go again the grain, "put your hand to the plow," "bring home the bacon"

**Expected behavior**
should be different quests 

**Screenshots**
<img width="1512" alt="Screenshot 2022-11-30 at 20 52 09" src="https://user-images.githubusercontent.com/119008588/204946904-d3b38570-938b-4022-bdae-f1a599c20882.png">

**Comment by GingaaBread** [comment]
More have been added
