### ISSUE TITLE
bring home the bacon has the wrong quest steps 

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#191]
**Describe the bug**
listing wrong quest steps 

**To Reproduce**
1. look at the quest

**Expected behavior**
should have goals to do with selling things

**Screenshots**
<img width="315" alt="Screenshot 2022-11-30 at 20 53 28" src="https://user-images.githubusercontent.com/119008588/204947047-9132ca05-2bb9-4595-bf28-c5735db224a8.png">

**Comment by GingaaBread** [comment]
Fixed (and added all others!)
