### ISSUE TITLE
not receiving quest rewards

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#192]
**Describe the bug**
I'm not getting the reward when I complete a step of a quest. 
**_Note:_** this may have to do with the fact i'm confused as to when i complete a quest. i thought it was when the panel refreshes with the checkmark animation.

**To Reproduce**
1. complete a step from a quest
2. don't get money 

**Expected behavior**
Should receive money from completing step.

**Comment by GingaaBread** [comment]
Added
