### ISSUE TITLE
quest steps should be out of 5

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#195]
**Describe the bug**
quests are x/4. it should be x/5 with the fifth step being the overall goal. 

**To Reproduce**
1. see quest section of hud / quest panel when you click it

**Expected behavior**
quests have five steps

**Screenshots**
<img width="219" alt="Screenshot 2022-11-30 at 20 59 00" src="https://user-images.githubusercontent.com/119008588/204947742-e4cea7b8-2877-4828-8502-20eb4a3e9a51.png">
<img width="1125" alt="Screenshot 2022-11-30 at 20 59 04" src="https://user-images.githubusercontent.com/119008588/204947747-75eb38ca-75fa-4dc9-9c1d-58131c4722c5.png">

**Comment by GingaaBread** [comment]
Fixed, but didn't have time to add the last "ultimate" step to the overview panel. But maybe that's not a bug, but a feature 😏 and it only displays the substeps? :D
