### ISSUE TITLE
bonus effects aren't visible on cards

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#197]
**Describe the bug**
can't see any card's bonus effects

**To Reproduce**
1. right click on card for more info
2. see card inspector

**Expected behavior**
bonus effects should be clearly listed 

**Scree
<img width="790" alt="Screenshot 2022-11-30 at 21 02 53" src="https://user-images.githubusercontent.com/119008588/204948193-d0951d49-563c-44c2-aecf-bb2583be3877.png">
nshots**

**Comment by GingaaBread** [comment]
Added by @rohaid-bakh
