### ISSUE TITLE
put your hand to the plow quest error

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#200]
**Describe the bug**
The third step of put your hand to the plow doesn't update as I place acres or pens.

**To Reproduce**
1. get put to the plow quest
2. get to step three
3. place any acres or pens
4. place 4 acres and 2 animal pens
5. place more than that 
6. see how nothing changes

**Expected behavior**
it should update and move you step 4 once complete

**Comment by GingaaBread** [comment]
Fixed
