### ISSUE TITLE
problem with cards / deck

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#203]
**Describe the bug**
Not sure how far reaching this is, but some of the cards seem to have too many copies. 
Ex. I've seen at least seven strawberry cards in a game, but there should only be six strawberry cards in the whole deck.

**To Reproduce**
1. count the cards you see?

**Expected behavior**
the number of cards in the deck should match the number in the card list

**Screenshots**

**Comment by GingaaBread** [comment]
fixed in recent
