### ISSUE TITLE
embed is big again

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#225]
**Describe the bug**
Where the game shows on the itch page used to be much smaller. It's size makes it a big difficult to navigate.

**To Reproduce**
1. Go to itch page

**Expected behavior**
The embed was much smaller before. I think the width of the banner at the top or possibly even smaller.

**Screenshots**
![Screenshot 2023-02-07 at 17 55 31](https://user-images.githubusercontent.com/119008588/217385571-8e99c6ec-0c15-4b78-b044-e8dfe77774b2.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Brave/Chrome

**Comment by GingaaBread** [comment]
Do you know the old dimensions? I see that on itch it's set to 1600x950 right now
