### ISSUE TITLE
odd resizing

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#227]
**Describe the bug**
When the game starts after clicking "new game," there's an odd resizing that feels a bit uncomfortable.

**To Reproduce**
1. Go to main menu
2. Click new game

**Expected behavior**
The photos should remain the same size when the letter appears.

**Screenshots**
https://user-images.githubusercontent.com/119008588/217386533-645a9ea1-67d4-4582-9189-c3c73deac3fe.mov

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: brave/chrome

**Comment by ballardi** [comment]
3024x1964 was endellions resolution

**Comment by cenheidlon** [comment]
1920x1200

**Comment by GingaaBread** [comment]
Kind of fixed, but HD+ will still feel somewhat off
