### ISSUE TITLE
detailed card view is super zoomed in

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#228]
**Describe the bug**
When you click to see the detailed card view, it's so zoomed in as to be illegible

**To Reproduce**
1. Right click on a card to see more info

**Expected behavior**
The detailed view should fit in the screen.

**Screenshots**
![Screenshot 2023-02-07 at 18 05 23 (2)](https://user-images.githubusercontent.com/119008588/217387392-0140b98a-3e43-4ca2-b6ef-b4f01b5c6994.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Brave/Chrome

**Comment by GingaaBread** [comment]
Weird, there's really a bunch of visuals bugs this build...
