### ISSUE TITLE
quest instruction resource images

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#229]
**Describe the bug**
the images only show next to the resource in step 4. also, the nut image never shows.

**To Reproduce**
1. Click on "view progress" to see all quests / steps

**Expected behavior**
The images should show in every step or in no steps.

**Screenshots**
![Screenshot 2023-02-07 at 18 14 43](https://user-images.githubusercontent.com/119008588/217388325-92cc65e0-413b-43c1-b7b9-084d1d24ce70.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome/brave

**Comment by GingaaBread** [comment]
Thanks for the heads-up, I forgot to add some icons to the Textmesh Pro sheet, will do so soon!
