### ISSUE TITLE
discard image

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#231]
**Describe the bug**
Before the animation plays after you hit "discard," the image is wrong.

**To Reproduce**
1. It was working at the beginning, so something happened that I'm not sure of. This was the 3rd or 4th card I discarded.
2. Select a card
3. Click "discard"

**Expected behavior**
The image should look like it always does. I think it's usually a trashcan

**Screenshots**
![Screenshot 2023-02-07 at 18 28 14](https://user-images.githubusercontent.com/119008588/217390399-4bd442fb-5e22-4fa6-a7a9-abb5202fd048.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome/brave

**Comment by GingaaBread** [comment]
That's weird. I'll check it out.

**Comment by GingaaBread** [comment]
Fixed
