### ISSUE TITLE
Shop Door SFX Not Triggering

### ISSUE THREAD

**Issue by GraySfx** [GingaaBread/Unity-Game-Jam-2022#232]
**Describe the bug**

When click on button to open the shop UI, there should be a Shop Door SFX triggered, which did not play on recent play through

**To Reproduce**
1. Start Game
2. Click Shop Door
3. No SFX Triggered

**Expected behavior**
When you click the "Shop" Button, it opens the shop UI and plays the Shop Door SFX Oneshot

**Desktop (please complete the following information):**

 - Browser: Safari

**Comment by GingaaBread** [comment]
ToggleReactor script related? Will check it out

**Comment by GingaaBread** [comment]
Probably related to FMOD

**Comment by GingaaBread** [comment]
Fixed
