### ISSUE TITLE
same quests each time

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#235]
**Describe the bug**
Every time I start a new game I get the three quests: A hard row to hoe, Put the bee on, and Squirrel away

**To Reproduce**
1. Start new game
2. See quests

**Expected behavior**
The quests should change each game

**Desktop (please complete the following information):**
 - Browser: chrome/brave

**Comment by GingaaBread** [comment]
Hm, I cannot reproduce:
![image](https://user-images.githubusercontent.com/26445308/217400227-efe671cd-456b-41f7-98ef-3dcd0f27cde0.png)
