### ISSUE TITLE
Player gets stuck

### ISSUE THREAD

**Issue by Crostz** [GingaaBread/Unity-Game-Jam-2022#69]
**Describe the bug**
Player cannot end the turn. They are stuck in the game. (End turn button is not working)

**To Reproduce**
1. Discard cards a lot.
2. End turn constantly after discarding all 5 cards. (Maybe its neccessary to place some of them aswell)
3. Eventually, after doing this a few times there will be a time where skipping the turn won't work.
4. See error.

**Expected behavior**
Keep playing

**Screenshots**
I'ts not easy to show as a screenshot. Its not a visual thing. It's more like clicking the button doesn't do anything.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: What version? Prototype?

**Additional context**
I was just skipping turns and discarding cards just so I can get my hands on acre/livestock cards.

**Comment by GingaaBread** [comment]
Buttons should be locked. Will be addressed in the locking mechanism card
