### ISSUE TITLE
Resolution Bug

### ISSUE THREAD

**Issue by Prudentibus** [GingaaBread/Unity-Game-Jam-2022#70]
**Describe the bug**
Camera resolution are not dedicated to specific resolution, that's lead to PLAYER to see borders of the map.

**To Reproduce**
Open a game on a mobile phone with resolution [2400 x 1080]

**Expected behavior**
Player can see borders of the map

**Screenshots**
![изображение](https://user-images.githubusercontent.com/118864015/203450415-34d7e528-1d8a-46eb-a23d-b69a0a4b4f41.png)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - OS: Android
 - Browser Mozila Firefox

**Additional context**
I consider, we should make game attached to specific resolution. Or if not in Unity, but rather on a page of Itch.Io

**Comment by GingaaBread** [comment]
Sounds like the next build should only support 16:9.
