### ISSUE TITLE
Mobile Touch Bug

### ISSUE THREAD

**Issue by Prudentibus** [GingaaBread/Unity-Game-Jam-2022#71]
**Describe the bug**
When PLAYER touch a screen on a phone, to pick up a card, it takes several cards.

**To Reproduce**
Click on a card, while playing on a Phone

**Expected behaviour**
Pressing on specific card. Would lead to another cards line up, and it makes them triggered on same place, when PLAYER pressed on a screen, even if it was fast touch.

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - OS: Android
 - Browser Mozila Firefox

**Additional context**
I consider this problem is irrelative at the moment, because this bug might be fixed, when there will be a confirmation of putting card on a tile.
But just in case, should log it off.

**Comment by GingaaBread** [comment]
Closed: mobile bugs won't be fixed. To be honest, I'm astounded it somewhat worked on mobile in the first place.
