### ISSUE TITLE
Mountain are invisible in the Winter

### ISSUE THREAD

**Issue by Prudentibus** [GingaaBread/Unity-Game-Jam-2022#72]
**Describe the bug**
When in game season is **winter**, the mountains are invisible, but they visible on other seasons  

**To Reproduce**
1. Click "End Turn" button;
2. Season changes to Winter;
3. Mountains become **invisible**;
4. Click "End Turn" till Winter season is over;
5. Mountains appear back.

**Expected behavior**
Mountains should be visible during all seasons.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/118864015/203451765-f782533b-9722-4f7c-8bf9-12120764bc35.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera
 - Version: irrelative 

**Additional context**
You **SHOULD** consider, that mountains appears on other seasons, but not on Winter. So mountains aren't deleted, they exist, but they aren't visible\replaced by frozen lake.

**Comment by rohaid-bakh** [comment]
Found out the cause of the bug: the wrong sprite was assigned for the mountains during winter. This has been fixed, thanks for bringing it up.
