### ISSUE TITLE
No Animation on changing seasons

### ISSUE THREAD

**Issue by Prudentibus** [GingaaBread/Unity-Game-Jam-2022#74]
**Describe the bug**
When PLAYER hits "End Turn" button multiply times ( spam it ), and gonna stop on specific season after first day, none of possible animation sequances aren't played.

**To Reproduce**
1. Press "End Turn" Button multiply times ( f.e. 8-12 times in a row )

**Expected behavior**
When new seasons starts, there should be animation of new season in "Time" Box.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - OS: Android
 - Browser Mozila Firefox

**Additional context**
I think we should disable "End Turn" button until new animation won't play. 
And it might be not neccary to review, since if we gonna play animation to new season for a full screen, it might work differently.
But just to add for a log.

**Comment by GingaaBread** [comment]
Fixed
