### ISSUE TITLE
Moving off hand and back causes wrong card to enlarge

### ISSUE THREAD

**Issue by samoncrief** [GingaaBread/Unity-Game-Jam-2022#95]
Moving the cursor off the side of a card does not cause the enlarged card to minimize if the cursor is over a different card before the animation finishes. When moving the cursor back onto the hand over a different card, the displayed card is placed over the previously enlarged card with new information. Moving between other cards changes the info but not the location of the enlarged card. Moving back over the enlarged card then over the hand normally returns the cards to normal.

**To Reproduce**
1. Hover over leftmost card
2. Quickly move cursor to rightmost card, passing over other cards
3. Hover cursor over non-enlarged cards to cause info change in place

**Expected behavior**
When the player is not hovering over a card, it should not be enlarged. If the player hovers over a card that is not enlarged while another card is enlarged, the enlarged card should return to normal and the current card should be enlarged.

**Screenshots**
![image](https://user-images.githubusercontent.com/51212088/203838814-caeb1e72-b1ab-4fe6-bc7b-9fe43fef5a70.png)
![image](https://user-images.githubusercontent.com/51212088/203839658-d2154656-9c8a-44ae-bb9d-b2b148f59293.png)
![image](https://user-images.githubusercontent.com/51212088/203839703-a176459b-ce93-4b2d-80eb-4dac3bd061b3.png)

**Comment by GingaaBread** [comment]
Closed for now
