### ISSUE TITLE
running out of cards

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#98]
**Describe the bug**
i ran out of cards after drawing 60 cards 

**To Reproduce**
Steps to reproduce the behaviour:
1. play / discard 5 cards every turn for 12 turns
2. receive no new cards
3. cannot click "end turn"

**Expected behaviour**
the player should continue receiving cards until they have gotten all 240 cards in the deck

**Desktop (please complete the following information):**
 - Browser [brave/chrome]

**Comment by ballardi** [comment]
i believe this is fixed now
